#!/bin/bash
#
# Idempotent script to set up Zabbix integration for speedtest
# Creates UserParameters config and installs zbx-speedtest.py script
# This script can be run multiple times safely
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"

# Zabbix configuration
ZABBIX_CONF_DIR="/etc/zabbix/zabbix_agentd.conf.d"
ZABBIX_SCRIPT_DIR="/usr/local/bin"
ZABBIX_CONF_FILE="$ZABBIX_CONF_DIR/speedtest.conf"
ZABBIX_SCRIPT="$ZABBIX_SCRIPT_DIR/zbx-speedtest.py"
PROJECT_SCRIPT="$PROJECT_DIR/zbx-speedtest.py"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

log_info "Setting up Zabbix integration for speedtest..."

# Check if Zabbix agent is installed
if ! command -v zabbix_agentd &> /dev/null && ! systemctl list-unit-files | grep -q zabbix-agent; then
    log_warn "Zabbix agent not found. Continuing anyway, but you may need to install it."
fi

# Create Zabbix config directory if it doesn't exist
if [ ! -d "$ZABBIX_CONF_DIR" ]; then
    log_info "Creating Zabbix config directory: $ZABBIX_CONF_DIR"
    mkdir -p "$ZABBIX_CONF_DIR"
    chown root:root "$ZABBIX_CONF_DIR"
    chmod 755 "$ZABBIX_CONF_DIR"
fi

# Check if project script exists
if [ ! -f "$PROJECT_SCRIPT" ]; then
    log_error "Speedtest script not found: $PROJECT_SCRIPT"
    exit 1
fi

# Copy script to /usr/local/bin
log_info "Installing zbx-speedtest.py to $ZABBIX_SCRIPT_DIR"
cp "$PROJECT_SCRIPT" "$ZABBIX_SCRIPT"
chown root:root "$ZABBIX_SCRIPT"
chmod 755 "$ZABBIX_SCRIPT"

# Create UserParameters config file
log_info "Creating Zabbix UserParameters config: $ZABBIX_CONF_FILE"

cat > "$ZABBIX_CONF_FILE" << 'EOF'
# Speedtest UserParameters for Zabbix
# Generated by setup_zabbix.sh
# Do not edit manually - this file will be overwritten by setup script

# Latest speedtest values
UserParameter=speedtest.download,/usr/local/bin/zbx-speedtest.py speedtest.download
UserParameter=speedtest.upload,/usr/local/bin/zbx-speedtest.py speedtest.upload
UserParameter=speedtest.ping,/usr/local/bin/zbx-speedtest.py speedtest.ping

# 24-hour averages
UserParameter=speedtest.download_avg_24h,/usr/local/bin/zbx-speedtest.py speedtest.download_avg_24h
UserParameter=speedtest.upload_avg_24h,/usr/local/bin/zbx-speedtest.py speedtest.upload_avg_24h
UserParameter=speedtest.ping_avg_24h,/usr/local/bin/zbx-speedtest.py speedtest.ping_avg_24h

# Test statistics
UserParameter=speedtest.test_count_24h,/usr/local/bin/zbx-speedtest.py speedtest.test_count_24h
UserParameter=speedtest.last_test_time,/usr/local/bin/zbx-speedtest.py speedtest.last_test_time

# Server information
UserParameter=speedtest.server_name,/usr/local/bin/zbx-speedtest.py speedtest.server_name
UserParameter=speedtest.server_location,/usr/local/bin/zbx-speedtest.py speedtest.server_location
UserParameter=speedtest.server_country,/usr/local/bin/zbx-speedtest.py speedtest.server_country
EOF

chown root:root "$ZABBIX_CONF_FILE"
chmod 644 "$ZABBIX_CONF_FILE"

log_info "Zabbix configuration file created: $ZABBIX_CONF_FILE"

# Test the script
log_info "Testing zbx-speedtest.py script..."
if "$ZABBIX_SCRIPT" speedtest.download > /dev/null 2>&1; then
    log_info "Script test successful"
else
    log_warn "Script test returned non-zero exit code (this is OK if no speedtest data exists yet)"
fi

# Check if Zabbix agent service exists and restart it
if systemctl list-unit-files | grep -q "zabbix-agent.service"; then
    log_info "Restarting Zabbix agent to load new configuration..."
    if systemctl restart zabbix-agent 2>/dev/null; then
        log_info "Zabbix agent restarted successfully"
    else
        log_warn "Could not restart Zabbix agent. You may need to restart it manually:"
        log_warn "  sudo systemctl restart zabbix-agent"
    fi
elif systemctl list-unit-files | grep -q "zabbix-agentd.service"; then
    log_info "Restarting Zabbix agent daemon to load new configuration..."
    if systemctl restart zabbix-agentd 2>/dev/null; then
        log_info "Zabbix agent daemon restarted successfully"
    else
        log_warn "Could not restart Zabbix agent daemon. You may need to restart it manually:"
        log_warn "  sudo systemctl restart zabbix-agentd"
    fi
else
    log_warn "Zabbix agent service not found. Please restart it manually after setup."
fi

log_info "Zabbix integration setup complete!"
log_info ""
log_info "Available metrics:"
log_info "  - speedtest.download (latest download speed in Mbps)"
log_info "  - speedtest.upload (latest upload speed in Mbps)"
log_info "  - speedtest.ping (latest ping in ms)"
log_info "  - speedtest.download_avg_24h (24h average download in Mbps)"
log_info "  - speedtest.upload_avg_24h (24h average upload in Mbps)"
log_info "  - speedtest.ping_avg_24h (24h average ping in ms)"
log_info "  - speedtest.test_count_24h (number of tests in last 24h)"
log_info "  - speedtest.last_test_time (Unix timestamp of last test)"
log_info "  - speedtest.server_name (name of last test server)"
log_info "  - speedtest.server_location (location of last test server)"
log_info "  - speedtest.server_country (country of last test server)"
log_info ""
log_info "Test the script manually:"
log_info "  /usr/local/bin/zbx-speedtest.py speedtest.download"
log_info ""
log_info "Configuration file: $ZABBIX_CONF_FILE"

